services:
  app:
    user: 1000:1000
    image: vaultureact:latest
    build: .
    environment:
      WATCHPACK_POLLING: true
      NEXT_WEBPACK_USEPOLLING: 1
    command: npm run dev
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules